# Generated by Django 2.1.2 on 2018-10-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('propertyImageID', models.CharField(max_length=200)),
                ('propertyImageDescription', models.CharField(max_length=500)),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Property')),
            ],
        ),
    ]
