# Generated by Django 2.1.3 on 2018-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181112_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='RoleCode',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.AddField(
            model_name='userrole',
            name='name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
