# Generated by Django 2.1.3 on 2018-11-15 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181115_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysFeature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userrole',
            name='dateAssigned',
            field=models.DateField(default=datetime.datetime(2018, 11, 15, 2, 49, 24, 381879)),
        ),
    ]
