# Generated by Django 2.1.3 on 2018-11-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181116_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='name',
            new_name='rolename',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='dateAssigned',
        ),
        migrations.AddField(
            model_name='userrole',
            name='username',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='rolecode',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
