# Generated by Django 2.1.2 on 2018-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181118_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysFeatureRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(default='admin', max_length=100)),
                ('featurename', models.CharField(default='add user', max_length=100)),
                ('permissiontype', models.CharField(default='read', max_length=100)),
            ],
        ),
    ]
